services:
    broadcast-whatsapp:
        container_name: broadcast-whatsapp
        build: .
        restart: always
        volumes:
            - .:/app
            - auth:/app/auth
        working_dir: /app
        command: ['pnpm', 'start']

volumes:
    auth:
