services:
    app:
        build: .
        container_name: bcast
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - TZ=Asia/Jakarta
        volumes:
            - ./auth:/usr/src/app/auth
